### ISSUE TITLE
Bei mir startet der bot nicht auf meiner VM

### ISSUE THREAD

**Issue by robinkaulfuss** [Neocraftr/griefergames-bot#2]
Ich habe jetzt die datei geklont aber wenn ich node bot.js eingebe geschieht nichts...Zudem weiß ich nicht wo ich die account daten eintagen soll....

**Comment by Neocraftr** [comment]
Das ist eine Bot Library und kein fertiger Bot. Den Bot musst du dir selbst wie im Beispiel unten gezeigt programmieren

**Comment by DJCoolDev** [comment]
Außerdem ein kleiner Tipp:
Sollte deine VM nicht Lokal bei dir laufen sondern über einen größeren Hoster, kann es sein, dass deine IP gebannt ist.

**Comment by robinkaulfuss** [comment]
Ah okay....Vielen Dank für den Tipp!
